import Head from "next/head"
import Image from "next/image"
import FloatBar from "../components/FloatBar"
import NavBar from "../components/NavBar"
import SideNavBar from "../components/SideNavBar"
import { Provider } from "react-redux"
import { store } from "./../redux/store"
import HeroSection from "../components/HeroSection"
import RecentNews from "../components/RecentNews"
import SideBar from "../components/SideBar"
import { NextPage } from "next"


const Home: NextPage = () => {
return (
    <div>
      <Head>
        <title>Blog-App </title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="bg-light">
          <NavBar />
          <SideNavBar />
          <FloatBar />
          <HeroSection />
          <div className="grid grid-cols-4 gap-6 px-5 mx-auto my-10 max-w-7xl">
            <RecentNews />
            <SideBar />
          </div>
        </main>
    </div>
  )
}

export default Home